// prettier-ignore

export const outlineMap = {
  // outline-width
  "outline-0": "ow-0",
  "outline-1": "ow-1",
  "outline-2": "ow-2",
  "outline-4": "ow-4",

  // outline-color
  "outline-red-50": "oc-l-red-6",
  "outline-red-100": "oc-l-red-5",
  "outline-red-200": "oc-l-red-4",
  "outline-red-300": "oc-l-red-3",
  "outline-red-400": "oc-l-red-2",
  "outline-red-500": "oc-red",
  "outline-red-600": "oc-d-red-2",
  "outline-red-700": "oc-d-red-3",
  "outline-red-800": "oc-d-red-4",
  "outline-red-900": "oc-d-red-5",
  "outline-red-950": "oc-d-red-6",

  "outline-orange-50": "oc-l-orange-6",
  "outline-orange-100": "oc-l-orange-5",
  "outline-orange-200": "oc-l-orange-4",
  "outline-orange-300": "oc-l-orange-3",
  "outline-orange-400": "oc-l-orange-2",
  "outline-orange-500": "oc-orange",
  "outline-orange-600": "oc-d-orange-2",
  "outline-orange-700": "oc-d-orange-3",
  "outline-orange-800": "oc-d-orange-4",
  "outline-orange-900": "oc-d-orange-5",
  "outline-orange-950": "oc-d-orange-6",

  "outline-yellow-50": "oc-l-yellow-6",
  "outline-yellow-100": "oc-l-yellow-5",
  "outline-yellow-200": "oc-l-yellow-4",
  "outline-yellow-300": "oc-l-yellow-3",
  "outline-yellow-400": "oc-l-yellow-2",
  "outline-yellow-500": "oc-yellow",
  "outline-yellow-600": "oc-d-yellow-2",
  "outline-yellow-700": "oc-d-yellow-3",
  "outline-yellow-800": "oc-d-yellow-4",
  "outline-yellow-900": "oc-d-yellow-5",
  "outline-yellow-950": "oc-d-yellow-6",

  "outline-green-50": "oc-l-green-6",
  "outline-green-100": "oc-l-green-5",
  "outline-green-200": "oc-l-green-4",
  "outline-green-300": "oc-l-green-3",
  "outline-green-400": "oc-l-green-2",
  "outline-green-500": "oc-green",
  "outline-green-600": "oc-d-green-2",
  "outline-green-700": "oc-d-green-3",
  "outline-green-800": "oc-d-green-4",
  "outline-green-900": "oc-d-green-5",
  "outline-green-950": "oc-d-green-6",

  "outline-teal-50": "oc-l-teal-6",
  "outline-teal-100": "oc-l-teal-5",
  "outline-teal-200": "oc-l-teal-4",
  "outline-teal-300": "oc-l-teal-3",
  "outline-teal-400": "oc-l-teal-2",
  "outline-teal-500": "oc-teal",
  "outline-teal-600": "oc-d-teal-2",
  "outline-teal-700": "oc-d-teal-3",
  "outline-teal-800": "oc-d-teal-4",
  "outline-teal-900": "oc-d-teal-5",
  "outline-teal-950": "oc-d-teal-6",

  "outline-cyan-50": "oc-l-cyan-6",
  "outline-cyan-100": "oc-l-cyan-5",
  "outline-cyan-200": "oc-l-cyan-4",
  "outline-cyan-300": "oc-l-cyan-3",
  "outline-cyan-400": "oc-l-cyan-2",
  "outline-cyan-500": "oc-cyan",
  "outline-cyan-600": "oc-d-cyan-2",
  "outline-cyan-700": "oc-d-cyan-3",
  "outline-cyan-800": "oc-d-cyan-4",
  "outline-cyan-900": "oc-d-cyan-5",
  "outline-cyan-950": "oc-d-cyan-6",

  "outline-blue-50": "oc-l-blue-6",
  "outline-blue-100": "oc-l-blue-5",
  "outline-blue-200": "oc-l-blue-4",
  "outline-blue-300": "oc-l-blue-3",
  "outline-blue-400": "oc-l-blue-2",
  "outline-blue-500": "oc-blue",
  "outline-blue-600": "oc-d-blue-2",
  "outline-blue-700": "oc-d-blue-3",
  "outline-blue-800": "oc-d-blue-4",
  "outline-blue-900": "oc-d-blue-5",
  "outline-blue-950": "oc-d-blue-6",

  "outline-indigo-50": "oc-l-indigo-6",
  "outline-indigo-100": "oc-l-indigo-5",
  "outline-indigo-200": "oc-l-indigo-4",
  "outline-indigo-300": "oc-l-indigo-3",
  "outline-indigo-400": "oc-l-indigo-2",
  "outline-indigo-500": "oc-indigo",
  "outline-indigo-600": "oc-d-indigo-2",
  "outline-indigo-700": "oc-d-indigo-3",
  "outline-indigo-800": "oc-d-indigo-4",
  "outline-indigo-900": "oc-d-indigo-5",
  "outline-indigo-950": "oc-d-indigo-6",

  "outline-violet-50": "oc-l-violet-6",
  "outline-violet-100": "oc-l-violet-5",
  "outline-violet-200": "oc-l-violet-4",
  "outline-violet-300": "oc-l-violet-3",
  "outline-violet-400": "oc-l-violet-2",
  "outline-violet-500": "oc-violet",
  "outline-violet-600": "oc-d-violet-2",
  "outline-violet-700": "oc-d-violet-3",
  "outline-violet-800": "oc-d-violet-4",
  "outline-violet-900": "oc-d-violet-5",
  "outline-violet-950": "oc-d-violet-6",

  "outline-pink-50": "oc-l-pink-6",
  "outline-pink-100": "oc-l-pink-5",
  "outline-pink-200": "oc-l-pink-4",
  "outline-pink-300": "oc-l-pink-3",
  "outline-pink-400": "oc-l-pink-2",
  "outline-pink-500": "oc-pink",
  "outline-pink-600": "oc-d-pink-2",
  "outline-pink-700": "oc-d-pink-3",
  "outline-pink-800": "oc-d-pink-4",
  "outline-pink-900": "oc-d-pink-5",
  "outline-pink-950": "oc-d-pink-6",

  "outline-gray-50": "oc-l-silver-6",
  "outline-gray-100": "oc-l-silver-5",
  "outline-gray-200": "oc-l-silver-4",
  "outline-gray-300": "oc-l-silver-3",
  "outline-gray-400": "oc-l-silver-2",
  "outline-gray-500": "oc-gray",
  "outline-gray-600": "oc-d-lead-2",
  "outline-gray-700": "oc-d-lead-3",
  "outline-gray-800": "oc-d-lead-4",
  "outline-gray-900": "oc-d-lead-5",
  "outline-gray-950": "oc-d-lead-6",

  "outline-black": "oc-black",
  "outline-transparent": "oc-transparent",
  "outline-white": "oc-white",

  // outline-style
  "outline-none": "os-none",
  "outline": "os-s",
  "outline-dashed": "os-d",

  // outline-offset
  "outline-offset-0": "oo-0",
  "outline-offset-1": "oo-1",
  "outline-offset-2": "oo-2",
  "outline-offset-4": "oo-4",
} as const;
