export const interactivityClasses = new Map<string, string>([
  // Accent Color
  ["accent-red-50", "ac-l-red-6"],
  ["accent-red-100", "ac-l-red-5"],
  ["accent-red-200", "ac-l-red-4"],
  ["accent-red-300", "ac-l-red-3"],
  ["accent-red-400", "ac-l-red-2"],
  ["accent-red-500", "ac-red"],
  ["accent-red-600", "ac-d-red-2"],
  ["accent-red-700", "ac-d-red-3"],
  ["accent-red-800", "ac-d-red-4"],
  ["accent-red-900", "ac-d-red-5"],
  ["accent-red-950", "ac-d-red-6"],

  ["accent-orange-50", "ac-l-orange-6"],
  ["accent-orange-100", "ac-l-orange-5"],
  ["accent-orange-200", "ac-l-orange-4"],
  ["accent-orange-300", "ac-l-orange-3"],
  ["accent-orange-400", "ac-l-orange-2"],
  ["accent-orange-500", "ac-orange"],
  ["accent-orange-600", "ac-d-orange-2"],
  ["accent-orange-700", "ac-d-orange-3"],
  ["accent-orange-800", "ac-d-orange-4"],
  ["accent-orange-900", "ac-d-orange-5"],
  ["accent-orange-950", "ac-d-orange-6"],

  ["accent-yellow-50", "ac-l-yellow-6"],
  ["accent-yellow-100", "ac-l-yellow-5"],
  ["accent-yellow-200", "ac-l-yellow-4"],
  ["accent-yellow-300", "ac-l-yellow-3"],
  ["accent-yellow-400", "ac-l-yellow-2"],
  ["accent-yellow-500", "ac-yellow"],
  ["accent-yellow-600", "ac-d-yellow-2"],
  ["accent-yellow-700", "ac-d-yellow-3"],
  ["accent-yellow-800", "ac-d-yellow-4"],
  ["accent-yellow-900", "ac-d-yellow-5"],
  ["accent-yellow-950", "ac-d-yellow-6"],

  ["accent-green-50", "ac-l-green-6"],
  ["accent-green-100", "ac-l-green-5"],
  ["accent-green-200", "ac-l-green-4"],
  ["accent-green-300", "ac-l-green-3"],
  ["accent-green-400", "ac-l-green-2"],
  ["accent-green-500", "ac-green"],
  ["accent-green-600", "ac-d-green-2"],
  ["accent-green-700", "ac-d-green-3"],
  ["accent-green-800", "ac-d-green-4"],
  ["accent-green-900", "ac-d-green-5"],
  ["accent-green-950", "ac-d-green-6"],

  ["accent-teal-50", "ac-l-teal-6"],
  ["accent-teal-100", "ac-l-teal-5"],
  ["accent-teal-200", "ac-l-teal-4"],
  ["accent-teal-300", "ac-l-teal-3"],
  ["accent-teal-400", "ac-l-teal-2"],
  ["accent-teal-500", "ac-teal"],
  ["accent-teal-600", "ac-d-teal-2"],
  ["accent-teal-700", "ac-d-teal-3"],
  ["accent-teal-800", "ac-d-teal-4"],
  ["accent-teal-900", "ac-d-teal-5"],
  ["accent-teal-950", "ac-d-teal-6"],

  ["accent-cyan-50", "ac-l-cyan-6"],
  ["accent-cyan-100", "ac-l-cyan-5"],
  ["accent-cyan-200", "ac-l-cyan-4"],
  ["accent-cyan-300", "ac-l-cyan-3"],
  ["accent-cyan-400", "ac-l-cyan-2"],
  ["accent-cyan-500", "ac-cyan"],
  ["accent-cyan-600", "ac-d-cyan-2"],
  ["accent-cyan-700", "ac-d-cyan-3"],
  ["accent-cyan-800", "ac-d-cyan-4"],
  ["accent-cyan-900", "ac-d-cyan-5"],
  ["accent-cyan-950", "ac-d-cyan-6"],

  ["accent-blue-50", "ac-l-blue-6"],
  ["accent-blue-100", "ac-l-blue-5"],
  ["accent-blue-200", "ac-l-blue-4"],
  ["accent-blue-300", "ac-l-blue-3"],
  ["accent-blue-400", "ac-l-blue-2"],
  ["accent-blue-500", "ac-blue"],
  ["accent-blue-600", "ac-d-blue-2"],
  ["accent-blue-700", "ac-d-blue-3"],
  ["accent-blue-800", "ac-d-blue-4"],
  ["accent-blue-900", "ac-d-blue-5"],
  ["accent-blue-950", "ac-d-blue-6"],

  ["accent-indigo-50", "ac-l-indigo-6"],
  ["accent-indigo-100", "ac-l-indigo-5"],
  ["accent-indigo-200", "ac-l-indigo-4"],
  ["accent-indigo-300", "ac-l-indigo-3"],
  ["accent-indigo-400", "ac-l-indigo-2"],
  ["accent-indigo-500", "ac-indigo"],
  ["accent-indigo-600", "ac-d-indigo-2"],
  ["accent-indigo-700", "ac-d-indigo-3"],
  ["accent-indigo-800", "ac-d-indigo-4"],
  ["accent-indigo-900", "ac-d-indigo-5"],
  ["accent-indigo-950", "ac-d-indigo-6"],

  ["accent-violet-50", "ac-l-violet-6"],
  ["accent-violet-100", "ac-l-violet-5"],
  ["accent-violet-200", "ac-l-violet-4"],
  ["accent-violet-300", "ac-l-violet-3"],
  ["accent-violet-400", "ac-l-violet-2"],
  ["accent-violet-500", "ac-violet"],
  ["accent-violet-600", "ac-d-violet-2"],
  ["accent-violet-700", "ac-d-violet-3"],
  ["accent-violet-800", "ac-d-violet-4"],
  ["accent-violet-900", "ac-d-violet-5"],
  ["accent-violet-950", "ac-d-violet-6"],

  ["accent-pink-50", "ac-l-pink-6"],
  ["accent-pink-100", "ac-l-pink-5"],
  ["accent-pink-200", "ac-l-pink-4"],
  ["accent-pink-300", "ac-l-pink-3"],
  ["accent-pink-400", "ac-l-pink-2"],
  ["accent-pink-500", "ac-pink"],
  ["accent-pink-600", "ac-d-pink-2"],
  ["accent-pink-700", "ac-d-pink-3"],
  ["accent-pink-800", "ac-d-pink-4"],
  ["accent-pink-900", "ac-d-pink-5"],
  ["accent-pink-950", "ac-d-pink-6"],

  ["accent-gray-50", "ac-l-silver-6"],
  ["accent-gray-100", "ac-l-silver-5"],
  ["accent-gray-200", "ac-l-silver-4"],
  ["accent-gray-300", "ac-l-silver-3"],
  ["accent-gray-400", "ac-l-silver-2"],
  ["accent-gray-500", "ac-gray"],
  ["accent-gray-600", "ac-d-lead-2"],
  ["accent-gray-700", "ac-d-lead-3"],
  ["accent-gray-800", "ac-d-lead-4"],
  ["accent-gray-900", "ac-d-lead-5"],
  ["accent-gray-950", "ac-d-lead-6"],

  // Appearance
  ["appearance-none", "a-none"],
  ["appearance-auto", "a-auto"],

  // Cursor
  ["cursor-auto", "c-auto"],
  ["cursor-default", "c-d"],
  ["cursor-pointer", "c-p"],
  ["cursor-wait", "c-w"],
  ["cursor-text", "c-t"],
  ["cursor-move", "c-m"],
  ["cursor-help", "c-h"],
  ["cursor-not-allowed", "c-na"],
  ["cursor-none", "c-none"],
  ["cursor-progress", "c-pr"],
  ["cursor-crosshair", "c-ch"],
  ["cursor-col-resize", "c-cr"],
  ["cursor-row-resize", "c-rs"],
  ["cursor-n-resize", "c-nr"],
  ["cursor-e-resize", "c-wr"],
  ["cursor-s-resize", "c-sr"],
  ["cursor-w-resize", "c-wr"],
  ["cursor-ne-resize", "c-ner"],
  ["cursor-nw-resize", "c-nwr"],
  ["cursor-se-resize", "c-ser"],
  ["cursor-sw-resize", "c-swr"],
  ["cursor-nesw-resize", "c-neswr"],
  ["cursor-nwse-resize", "c-nwser"],
  ["cursor-zoom-in", "c-zi"],
  ["cursor-zoom-out", "c-zo"],

  // Caret Color
  ["caret-red-50", "cc-l-red-6"],
  ["caret-red-100", "cc-l-red-5"],
  ["caret-red-200", "cc-l-red-4"],
  ["caret-red-300", "cc-l-red-3"],
  ["caret-red-400", "cc-l-red-2"],
  ["caret-red-500", "cc-red"],
  ["caret-red-600", "cc-d-red-2"],
  ["caret-red-700", "cc-d-red-3"],
  ["caret-red-800", "cc-d-red-4"],
  ["caret-red-900", "cc-d-red-5"],
  ["caret-red-950", "cc-d-red-6"],

  ["caret-orange-50", "cc-l-orange-6"],
  ["caret-orange-100", "cc-l-orange-5"],
  ["caret-orange-200", "cc-l-orange-4"],
  ["caret-orange-300", "cc-l-orange-3"],
  ["caret-orange-400", "cc-l-orange-2"],
  ["caret-orange-500", "cc-orange"],
  ["caret-orange-600", "cc-d-orange-2"],
  ["caret-orange-700", "cc-d-orange-3"],
  ["caret-orange-800", "cc-d-orange-4"],
  ["caret-orange-900", "cc-d-orange-5"],
  ["caret-orange-950", "cc-d-orange-6"],

  ["caret-yellow-50", "cc-l-yellow-6"],
  ["caret-yellow-100", "cc-l-yellow-5"],
  ["caret-yellow-200", "cc-l-yellow-4"],
  ["caret-yellow-300", "cc-l-yellow-3"],
  ["caret-yellow-400", "cc-l-yellow-2"],
  ["caret-yellow-500", "cc-yellow"],
  ["caret-yellow-600", "cc-d-yellow-2"],
  ["caret-yellow-700", "cc-d-yellow-3"],
  ["caret-yellow-800", "cc-d-yellow-4"],
  ["caret-yellow-900", "cc-d-yellow-5"],
  ["caret-yellow-950", "cc-d-yellow-6"],

  ["caret-green-50", "cc-l-green-6"],
  ["caret-green-100", "cc-l-green-5"],
  ["caret-green-200", "cc-l-green-4"],
  ["caret-green-300", "cc-l-green-3"],
  ["caret-green-400", "cc-l-green-2"],
  ["caret-green-500", "cc-green"],
  ["caret-green-600", "cc-d-green-2"],
  ["caret-green-700", "cc-d-green-3"],
  ["caret-green-800", "cc-d-green-4"],
  ["caret-green-900", "cc-d-green-5"],
  ["caret-green-950", "cc-d-green-6"],

  ["caret-teal-50", "cc-l-teal-6"],
  ["caret-teal-100", "cc-l-teal-5"],
  ["caret-teal-200", "cc-l-teal-4"],
  ["caret-teal-300", "cc-l-teal-3"],
  ["caret-teal-400", "cc-l-teal-2"],
  ["caret-teal-500", "cc-teal"],
  ["caret-teal-600", "cc-d-teal-2"],
  ["caret-teal-700", "cc-d-teal-3"],
  ["caret-teal-800", "cc-d-teal-4"],
  ["caret-teal-900", "cc-d-teal-5"],
  ["caret-teal-950", "cc-d-teal-6"],

  ["caret-cyan-50", "cc-l-cyan-6"],
  ["caret-cyan-100", "cc-l-cyan-5"],
  ["caret-cyan-200", "cc-l-cyan-4"],
  ["caret-cyan-300", "cc-l-cyan-3"],
  ["caret-cyan-400", "cc-l-cyan-2"],
  ["caret-cyan-500", "cc-cyan"],
  ["caret-cyan-600", "cc-d-cyan-2"],
  ["caret-cyan-700", "cc-d-cyan-3"],
  ["caret-cyan-800", "cc-d-cyan-4"],
  ["caret-cyan-900", "cc-d-cyan-5"],
  ["caret-cyan-950", "cc-d-cyan-6"],

  ["caret-blue-50", "cc-l-blue-6"],
  ["caret-blue-100", "cc-l-blue-5"],
  ["caret-blue-200", "cc-l-blue-4"],
  ["caret-blue-300", "cc-l-blue-3"],
  ["caret-blue-400", "cc-l-blue-2"],
  ["caret-blue-500", "cc-blue"],
  ["caret-blue-600", "cc-d-blue-2"],
  ["caret-blue-700", "cc-d-blue-3"],
  ["caret-blue-800", "cc-d-blue-4"],
  ["caret-blue-900", "cc-d-blue-5"],
  ["caret-blue-950", "cc-d-blue-6"],

  ["caret-indigo-50", "cc-l-indigo-6"],
  ["caret-indigo-100", "cc-l-indigo-5"],
  ["caret-indigo-200", "cc-l-indigo-4"],
  ["caret-indigo-300", "cc-l-indigo-3"],
  ["caret-indigo-400", "cc-l-indigo-2"],
  ["caret-indigo-500", "cc-indigo"],
  ["caret-indigo-600", "cc-d-indigo-2"],
  ["caret-indigo-700", "cc-d-indigo-3"],
  ["caret-indigo-800", "cc-d-indigo-4"],
  ["caret-indigo-900", "cc-d-indigo-5"],
  ["caret-indigo-950", "cc-d-indigo-6"],

  ["caret-violet-50", "cc-l-violet-6"],
  ["caret-violet-100", "cc-l-violet-5"],
  ["caret-violet-200", "cc-l-violet-4"],
  ["caret-violet-300", "cc-l-violet-3"],
  ["caret-violet-400", "cc-l-violet-2"],
  ["caret-violet-500", "cc-violet"],
  ["caret-violet-600", "cc-d-violet-2"],
  ["caret-violet-700", "cc-d-violet-3"],
  ["caret-violet-800", "cc-d-violet-4"],
  ["caret-violet-900", "cc-d-violet-5"],
  ["caret-violet-950", "cc-d-violet-6"],

  ["caret-pink-50", "cc-l-pink-6"],
  ["caret-pink-100", "cc-l-pink-5"],
  ["caret-pink-200", "cc-l-pink-4"],
  ["caret-pink-300", "cc-l-pink-3"],
  ["caret-pink-400", "cc-l-pink-2"],
  ["caret-pink-500", "cc-pink"],
  ["caret-pink-600", "cc-d-pink-2"],
  ["caret-pink-700", "cc-d-pink-3"],
  ["caret-pink-800", "cc-d-pink-4"],
  ["caret-pink-900", "cc-d-pink-5"],
  ["caret-pink-950", "cc-d-pink-6"],

  ["caret-gray-50", "cc-l-silver-6"],
  ["caret-gray-100", "cc-l-silver-5"],
  ["caret-gray-200", "cc-l-silver-4"],
  ["caret-gray-300", "cc-l-silver-3"],
  ["caret-gray-400", "cc-l-silver-2"],
  ["caret-gray-500", "cc-gray"],
  ["caret-gray-600", "cc-d-lead-2"],
  ["caret-gray-700", "cc-d-lead-3"],
  ["caret-gray-800", "cc-d-lead-4"],
  ["caret-gray-900", "cc-d-lead-5"],
  ["caret-gray-950", "cc-d-lead-6"],

  ["caret-black", "cc-black"],
  ["caret-transparent", "cc-transparent"],
  ["caret-white", "cc-white"],

  // Pointer Events
  ["pointer-events-none", "pe-none"],
  ["pointer-events-auto", "pe-auto"],

  // Resize
  ["resize-none", "r-none"],
  ["resize-y", "r-v"],
  ["resize-x", "r-h"],
  ["resize", "r-b"],

  // User Select
  ["select-none", "us-none"],
  ["select-text", "us-t"],
  ["select-all", "us-a"],
  ["select-auto", "us-auto"],
]);
