export const typographyClasses = new Map<string, string>([
  // Font Family
  ["font-sans", "ff-s"],
  ["font-serif", "ff-c"],
  ["font-mono", "ff-m"],

  // Font Size
  ["text-xs", "fs-xs"],
  ["text-base", "fs-b"],
  ["text-2xl", "fs-sm"],
  ["text-4xl", "fs-md"],
  ["text-5xl", "fs-lg"],
  ["text-6xl", "fs-xl"],
  ["text-7xl", "fs-xxl"],
  ["text-8xl", "fs-6xl"],

  // Font Style
  ["italic", "fs-i"],
  ["not-italic", "fs-n"],

  // Font Weight
  ["font-thin", "fw-100"],
  ["font-extralight", "fw-200"],
  ["font-light", "fw-300"],
  ["font-normal", "fw-400"],
  ["font-medium", "fw-500"],
  ["font-semibold", "fw-600"],
  ["font-bold", "fw-700"],
  ["font-extrabold", "fw-800"],
  ["font-black", "fw-900"],

  // Line Height
  ["leading-6", "lh-4"],
  ["leading-8", "lh-6"],
  ["leading-none", "lh-1"],
  ["leading-tight", "lh-2"],
  ["leading-snug", "lh-3"],
  ["leading-normal", "lh-4"],
  ["leading-relaxed", "lh-5"],
  ["leading-loose", "lh-6"],

  // List Style Type
  ["list-disc", "lst-d"],

  // Text Align
  ["text-left", "ta-l"],
  ["text-center", "ta-c"],
  ["text-right", "ta-r"],
  ["text-justify", "ta-j"],
  ["text-start", "ta-s"],
  ["text-end", "ta-e"],

  // Text Color
  ["text-red-50", "tc-l-red-6"],
  ["text-red-100", "tc-l-red-5"],
  ["text-red-200", "tc-l-red-4"],
  ["text-red-300", "tc-l-red-3"],
  ["text-red-400", "tc-l-red-2"],
  ["text-red-500", "tc-red"],
  ["text-red-600", "tc-d-red-2"],
  ["text-red-700", "tc-d-red-3"],
  ["text-red-800", "tc-d-red-4"],
  ["text-red-900", "tc-d-red-5"],
  ["text-red-950", "tc-d-red-6"],

  ["text-orange-50", "tc-l-orange-6"],
  ["text-orange-100", "tc-l-orange-5"],
  ["text-orange-200", "tc-l-orange-4"],
  ["text-orange-300", "tc-l-orange-3"],
  ["text-orange-400", "tc-l-orange-2"],
  ["text-orange-500", "tc-orange"],
  ["text-orange-600", "tc-d-orange-2"],
  ["text-orange-700", "tc-d-orange-3"],
  ["text-orange-800", "tc-d-orange-4"],
  ["text-orange-900", "tc-d-orange-5"],
  ["text-orange-950", "tc-d-orange-6"],

  ["text-yellow-50", "tc-l-yellow-6"],
  ["text-yellow-100", "tc-l-yellow-5"],
  ["text-yellow-200", "tc-l-yellow-4"],
  ["text-yellow-300", "tc-l-yellow-3"],
  ["text-yellow-400", "tc-l-yellow-2"],
  ["text-yellow-500", "tc-yellow"],
  ["text-yellow-600", "tc-d-yellow-2"],
  ["text-yellow-700", "tc-d-yellow-3"],
  ["text-yellow-800", "tc-d-yellow-4"],
  ["text-yellow-900", "tc-d-yellow-5"],
  ["text-yellow-950", "tc-d-yellow-6"],

  ["text-green-50", "tc-l-green-6"],
  ["text-green-100", "tc-l-green-5"],
  ["text-green-200", "tc-l-green-4"],
  ["text-green-300", "tc-l-green-3"],
  ["text-green-400", "tc-l-green-2"],
  ["text-green-500", "tc-green"],
  ["text-green-600", "tc-d-green-2"],
  ["text-green-700", "tc-d-green-3"],
  ["text-green-800", "tc-d-green-4"],
  ["text-green-900", "tc-d-green-5"],
  ["text-green-950", "tc-d-green-6"],

  ["text-teal-50", "tc-l-teal-6"],
  ["text-teal-100", "tc-l-teal-5"],
  ["text-teal-200", "tc-l-teal-4"],
  ["text-teal-300", "tc-l-teal-3"],
  ["text-teal-400", "tc-l-teal-2"],
  ["text-teal-500", "tc-teal"],
  ["text-teal-600", "tc-d-teal-2"],
  ["text-teal-700", "tc-d-teal-3"],
  ["text-teal-800", "tc-d-teal-4"],
  ["text-teal-900", "tc-d-teal-5"],
  ["text-teal-950", "tc-d-teal-6"],

  ["text-cyan-50", "tc-l-cyan-6"],
  ["text-cyan-100", "tc-l-cyan-5"],
  ["text-cyan-200", "tc-l-cyan-4"],
  ["text-cyan-300", "tc-l-cyan-3"],
  ["text-cyan-400", "tc-l-cyan-2"],
  ["text-cyan-500", "tc-cyan"],
  ["text-cyan-600", "tc-d-cyan-2"],
  ["text-cyan-700", "tc-d-cyan-3"],
  ["text-cyan-800", "tc-d-cyan-4"],
  ["text-cyan-900", "tc-d-cyan-5"],
  ["text-cyan-950", "tc-d-cyan-6"],

  ["text-blue-50", "tc-l-blue-6"],
  ["text-blue-100", "tc-l-blue-5"],
  ["text-blue-200", "tc-l-blue-4"],
  ["text-blue-300", "tc-l-blue-3"],
  ["text-blue-400", "tc-l-blue-2"],
  ["text-blue-500", "tc-blue"],
  ["text-blue-600", "tc-d-blue-2"],
  ["text-blue-700", "tc-d-blue-3"],
  ["text-blue-800", "tc-d-blue-4"],
  ["text-blue-900", "tc-d-blue-5"],
  ["text-blue-950", "tc-d-blue-6"],

  ["text-indigo-50", "tc-l-indigo-6"],
  ["text-indigo-100", "tc-l-indigo-5"],
  ["text-indigo-200", "tc-l-indigo-4"],
  ["text-indigo-300", "tc-l-indigo-3"],
  ["text-indigo-400", "tc-l-indigo-2"],
  ["text-indigo-500", "tc-indigo"],
  ["text-indigo-600", "tc-d-indigo-2"],
  ["text-indigo-700", "tc-d-indigo-3"],
  ["text-indigo-800", "tc-d-indigo-4"],
  ["text-indigo-900", "tc-d-indigo-5"],
  ["text-indigo-950", "tc-d-indigo-6"],

  ["text-violet-50", "tc-l-violet-6"],
  ["text-violet-100", "tc-l-violet-5"],
  ["text-violet-200", "tc-l-violet-4"],
  ["text-violet-300", "tc-l-violet-3"],
  ["text-violet-400", "tc-l-violet-2"],
  ["text-violet-500", "tc-violet"],
  ["text-violet-600", "tc-d-violet-2"],
  ["text-violet-700", "tc-d-violet-3"],
  ["text-violet-800", "tc-d-violet-4"],
  ["text-violet-900", "tc-d-violet-5"],
  ["text-violet-950", "tc-d-violet-6"],

  ["text-pink-50", "tc-l-pink-6"],
  ["text-pink-100", "tc-l-pink-5"],
  ["text-pink-200", "tc-l-pink-4"],
  ["text-pink-300", "tc-l-pink-3"],
  ["text-pink-400", "tc-l-pink-2"],
  ["text-pink-500", "tc-pink"],
  ["text-pink-600", "tc-d-pink-2"],
  ["text-pink-700", "tc-d-pink-3"],
  ["text-pink-800", "tc-d-pink-4"],
  ["text-pink-900", "tc-d-pink-5"],
  ["text-pink-950", "tc-d-pink-6"],

  ["text-gray-50", "tc-l-silver-6"],
  ["text-gray-100", "tc-l-silver-5"],
  ["text-gray-200", "tc-l-silver-4"],
  ["text-gray-300", "tc-l-silver-3"],
  ["text-gray-400", "tc-l-silver-2"],
  ["text-gray-500", "tc-gray"],
  ["text-gray-600", "tc-d-lead-2"],
  ["text-gray-700", "tc-d-lead-3"],
  ["text-gray-800", "tc-d-lead-4"],
  ["text-gray-900", "tc-d-lead-5"],
  ["text-gray-950", "tc-d-lead-6"],

  ["text-black", "tc-black"],
  ["text-transparent", "tc-transparent"],
  ["text-white", "tc-white"],

  // Text Decoration
  ["underline", "td-u"],
  ["no-underline", "td-none"],

  // Text Decoration Color
  ["decoration-red-50", "tdc-l-red-6"],
  ["decoration-red-100", "tdc-l-red-5"],
  ["decoration-red-200", "tdc-l-red-4"],
  ["decoration-red-300", "tdc-l-red-3"],
  ["decoration-red-400", "tdc-l-red-2"],
  ["decoration-red-500", "tdc-red"],
  ["decoration-red-600", "tdc-d-red-2"],
  ["decoration-red-700", "tdc-d-red-3"],
  ["decoration-red-800", "tdc-d-red-4"],
  ["decoration-red-900", "tdc-d-red-5"],
  ["decoration-red-950", "tdc-d-red-6"],

  ["decoration-orange-50", "tdc-l-orange-6"],
  ["decoration-orange-100", "tdc-l-orange-5"],
  ["decoration-orange-200", "tdc-l-orange-4"],
  ["decoration-orange-300", "tdc-l-orange-3"],
  ["decoration-orange-400", "tdc-l-orange-2"],
  ["decoration-orange-500", "tdc-orange"],
  ["decoration-orange-600", "tdc-d-orange-2"],
  ["decoration-orange-700", "tdc-d-orange-3"],
  ["decoration-orange-800", "tdc-d-orange-4"],
  ["decoration-orange-900", "tdc-d-orange-5"],
  ["decoration-orange-950", "tdc-d-orange-6"],

  ["decoration-yellow-50", "tdc-l-yellow-6"],
  ["decoration-yellow-100", "tdc-l-yellow-5"],
  ["decoration-yellow-200", "tdc-l-yellow-4"],
  ["decoration-yellow-300", "tdc-l-yellow-3"],
  ["decoration-yellow-400", "tdc-l-yellow-2"],
  ["decoration-yellow-500", "tdc-yellow"],
  ["decoration-yellow-600", "tdc-d-yellow-2"],
  ["decoration-yellow-700", "tdc-d-yellow-3"],
  ["decoration-yellow-800", "tdc-d-yellow-4"],
  ["decoration-yellow-900", "tdc-d-yellow-5"],
  ["decoration-yellow-950", "tdc-d-yellow-6"],

  ["decoration-green-50", "tdc-l-green-6"],
  ["decoration-green-100", "tdc-l-green-5"],
  ["decoration-green-200", "tdc-l-green-4"],
  ["decoration-green-300", "tdc-l-green-3"],
  ["decoration-green-400", "tdc-l-green-2"],
  ["decoration-green-500", "tdc-green"],
  ["decoration-green-600", "tdc-d-green-2"],
  ["decoration-green-700", "tdc-d-green-3"],
  ["decoration-green-800", "tdc-d-green-4"],
  ["decoration-green-900", "tdc-d-green-5"],
  ["decoration-green-950", "tdc-d-green-6"],

  ["decoration-teal-50", "tdc-l-teal-6"],
  ["decoration-teal-100", "tdc-l-teal-5"],
  ["decoration-teal-200", "tdc-l-teal-4"],
  ["decoration-teal-300", "tdc-l-teal-3"],
  ["decoration-teal-400", "tdc-l-teal-2"],
  ["decoration-teal-500", "tdc-teal"],
  ["decoration-teal-600", "tdc-d-teal-2"],
  ["decoration-teal-700", "tdc-d-teal-3"],
  ["decoration-teal-800", "tdc-d-teal-4"],
  ["decoration-teal-900", "tdc-d-teal-5"],
  ["decoration-teal-950", "tdc-d-teal-6"],

  ["decoration-cyan-50", "tdc-l-cyan-6"],
  ["decoration-cyan-100", "tdc-l-cyan-5"],
  ["decoration-cyan-200", "tdc-l-cyan-4"],
  ["decoration-cyan-300", "tdc-l-cyan-3"],
  ["decoration-cyan-400", "tdc-l-cyan-2"],
  ["decoration-cyan-500", "tdc-cyan"],
  ["decoration-cyan-600", "tdc-d-cyan-2"],
  ["decoration-cyan-700", "tdc-d-cyan-3"],
  ["decoration-cyan-800", "tdc-d-cyan-4"],
  ["decoration-cyan-900", "tdc-d-cyan-5"],
  ["decoration-cyan-950", "tdc-d-cyan-6"],

  ["decoration-blue-50", "tdc-l-blue-6"],
  ["decoration-blue-100", "tdc-l-blue-5"],
  ["decoration-blue-200", "tdc-l-blue-4"],
  ["decoration-blue-300", "tdc-l-blue-3"],
  ["decoration-blue-400", "tdc-l-blue-2"],
  ["decoration-blue-500", "tdc-blue"],
  ["decoration-blue-600", "tdc-d-blue-2"],
  ["decoration-blue-700", "tdc-d-blue-3"],
  ["decoration-blue-800", "tdc-d-blue-4"],
  ["decoration-blue-900", "tdc-d-blue-5"],
  ["decoration-blue-950", "tdc-d-blue-6"],

  ["decoration-indigo-50", "tdc-l-indigo-6"],
  ["decoration-indigo-100", "tdc-l-indigo-5"],
  ["decoration-indigo-200", "tdc-l-indigo-4"],
  ["decoration-indigo-300", "tdc-l-indigo-3"],
  ["decoration-indigo-400", "tdc-l-indigo-2"],
  ["decoration-indigo-500", "tdc-indigo"],
  ["decoration-indigo-600", "tdc-d-indigo-2"],
  ["decoration-indigo-700", "tdc-d-indigo-3"],
  ["decoration-indigo-800", "tdc-d-indigo-4"],
  ["decoration-indigo-900", "tdc-d-indigo-5"],
  ["decoration-indigo-950", "tdc-d-indigo-6"],

  ["decoration-violet-50", "tdc-l-violet-6"],
  ["decoration-violet-100", "tdc-l-violet-5"],
  ["decoration-violet-200", "tdc-l-violet-4"],
  ["decoration-violet-300", "tdc-l-violet-3"],
  ["decoration-violet-400", "tdc-l-violet-2"],
  ["decoration-violet-500", "tdc-violet"],
  ["decoration-violet-600", "tdc-d-violet-2"],
  ["decoration-violet-700", "tdc-d-violet-3"],
  ["decoration-violet-800", "tdc-d-violet-4"],
  ["decoration-violet-900", "tdc-d-violet-5"],
  ["decoration-violet-950", "tdc-d-violet-6"],

  ["decoration-pink-50", "tdc-l-pink-6"],
  ["decoration-pink-100", "tdc-l-pink-5"],
  ["decoration-pink-200", "tdc-l-pink-4"],
  ["decoration-pink-300", "tdc-l-pink-3"],
  ["decoration-pink-400", "tdc-l-pink-2"],
  ["decoration-pink-500", "tdc-pink"],
  ["decoration-pink-600", "tdc-d-pink-2"],
  ["decoration-pink-700", "tdc-d-pink-3"],
  ["decoration-pink-800", "tdc-d-pink-4"],
  ["decoration-pink-900", "tdc-d-pink-5"],
  ["decoration-pink-950", "tdc-d-pink-6"],

  ["decoration-gray-50", "tdc-l-silver-6"],
  ["decoration-gray-100", "tdc-l-silver-5"],
  ["decoration-gray-200", "tdc-l-silver-4"],
  ["decoration-gray-300", "tdc-l-silver-3"],
  ["decoration-gray-400", "tdc-l-silver-2"],
  ["decoration-gray-500", "tdc-gray"],
  ["decoration-gray-600", "tdc-d-lead-2"],
  ["decoration-gray-700", "tdc-d-lead-3"],
  ["decoration-gray-800", "tdc-d-lead-4"],
  ["decoration-gray-900", "tdc-d-lead-5"],
  ["decoration-gray-950", "tdc-d-lead-6"],

  ["decoration-black", "tdc-black"],
  ["decoration-transparent", "tdc-transparent"],
  ["decoration-white", "tdc-white"],

  // Text Decoration Style
  ["decoration-solid", "tds-s"],
  ["decoration-dashed", "tds-d"],

  // Text Decoration Thickness
  ["decoration-auto", "tdt-auto"],
  ["decoration-from-font", "tdt-ff"],
  ["decoration-0", "tdt-0"],
  ["decoration-1", "tdt-1"],
  ["decoration-2", "tdt-2"],
  ["decoration-4", "tdt-4"],

  // Word Break
  ["break-normal", "ow-n"],
  ["break-words", "ow-bw"],
]);
